"""create schema tables

Revision ID: 1f8f95ad327b
Revises: 9739a6693138
Create Date: 2026-05-01 12:42:32.483441

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f8f95ad327b"
down_revision: Union[str, Sequence[str], None] = "9739a6693138"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_article_matches",
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("processed_article_id", sa.Integer(), nullable=False),
        sa.Column("matched_supplier", sa.String(length=255), nullable=True),
        sa.Column("matched_region", sa.String(length=255), nullable=True),
        sa.Column("matched_category", sa.String(length=255), nullable=True),
        sa.Column("matched_event_id", sa.String(length=100), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("reason_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_matched_supplier", "news_article_matches", ["matched_supplier"], unique=False
    )
    op.create_index(
        "idx_user_article",
        "news_article_matches",
        ["user_id", "processed_article_id"],
        unique=False,
    )
    op.create_table(
        "news_articles_processed",
        sa.Column("raw_article_id", sa.Integer(), nullable=False),
        sa.Column("normalized_title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("top_level_category", sa.String(length=50), nullable=False),
        sa.Column("signal_tags", sa.JSON(), nullable=True),
        sa.Column("priority_signal", sa.String(length=100), nullable=True),
        sa.Column("detected_regions", sa.JSON(), nullable=True),
        sa.Column("detected_suppliers", sa.JSON(), nullable=True),
        sa.Column("detected_categories", sa.JSON(), nullable=True),
        sa.Column("signal_score", sa.Float(), nullable=False),
        sa.Column("processing_status", sa.String(length=20), nullable=False),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_processed_at", "news_articles_processed", ["processed_at"], unique=False)
    op.create_index(
        "idx_raw_article_id", "news_articles_processed", ["raw_article_id"], unique=False
    )
    op.create_index("idx_signal_score", "news_articles_processed", ["signal_score"], unique=False)
    op.create_index(
        "idx_top_level_category", "news_articles_processed", ["top_level_category"], unique=False
    )
    op.create_table(
        "news_articles_raw",
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_article_id", sa.String(length=255), nullable=True),
        sa.Column("query_group", sa.String(length=100), nullable=False),
        sa.Column("ingest_hash", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content_snippet", sa.Text(), nullable=True),
        sa.Column("article_url", sa.String(length=2000), nullable=False),
        sa.Column("canonical_url", sa.String(length=2000), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("raw_payload_json", sa.JSON(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ingest_hash"),
    )
    op.create_index("idx_ingest_hash", "news_articles_raw", ["ingest_hash"], unique=False)
    op.create_index(
        "idx_provider_article_id",
        "news_articles_raw",
        ["provider", "provider_article_id"],
        unique=False,
    )
    op.create_index("idx_published_at", "news_articles_raw", ["published_at"], unique=False)
    op.create_index("idx_source_name", "news_articles_raw", ["source_name"], unique=False)
    op.create_table(
        "news_pipeline_runs",
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("articles_fetched", sa.Integer(), nullable=False),
        sa.Column("articles_kept", sa.Integer(), nullable=False),
        sa.Column("articles_rejected", sa.Integer(), nullable=False),
        sa.Column("duplicates_removed", sa.Integer(), nullable=False),
        sa.Column("articles_sent_to_llm", sa.Integer(), nullable=False),
        sa.Column("feeds_materialized", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_pipeline_runs_started_at", "news_pipeline_runs", ["started_at"], unique=False
    )
    op.create_index("idx_pipeline_runs_status", "news_pipeline_runs", ["status"], unique=False)
    op.create_table(
        "news_priority_events",
        sa.Column("processed_article_id", sa.Integer(), nullable=False),
        sa.Column("priority_type", sa.String(length=50), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("dispatch_window", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_priority_type", "news_priority_events", ["priority_type"], unique=False)
    op.create_index("idx_priority_events_status", "news_priority_events", ["status"], unique=False)
    op.create_table(
        "user_news_feed",
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("processed_article_id", sa.Integer(), nullable=False),
        sa.Column("top_level_category", sa.String(length=50), nullable=False),
        sa.Column("rank_score", sa.Float(), nullable=False),
        sa.Column("match_reasons", sa.JSON(), nullable=False),
        sa.Column("related_sourcing_event_ids", sa.JSON(), nullable=True),
        sa.Column("surfaced_at", sa.DateTime(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_rank_score", "user_news_feed", ["rank_score"], unique=False)
    op.create_index("idx_user_feed_user_id", "user_news_feed", ["user_id"], unique=False)
    op.create_index("idx_user_surfaced", "user_news_feed", ["user_id", "surfaced_at"], unique=False)
    op.create_table(
        "user_news_preferences",
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("preferred_categories", sa.JSON(), nullable=False),
        sa.Column("preferred_suppliers", sa.JSON(), nullable=False),
        sa.Column("preferred_regions", sa.JSON(), nullable=False),
        sa.Column("excluded_topics", sa.JSON(), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "idx_user_preferences_user_id", "user_news_preferences", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_preferences_user_id", table_name="user_news_preferences")
    op.drop_table("user_news_preferences")
    op.drop_index("idx_user_surfaced", table_name="user_news_feed")
    op.drop_index("idx_user_feed_user_id", table_name="user_news_feed")
    op.drop_index("idx_rank_score", table_name="user_news_feed")
    op.drop_table("user_news_feed")
    op.drop_index("idx_priority_events_status", table_name="news_priority_events")
    op.drop_index("idx_priority_type", table_name="news_priority_events")
    op.drop_table("news_priority_events")
    op.drop_index("idx_pipeline_runs_status", table_name="news_pipeline_runs")
    op.drop_index("idx_pipeline_runs_started_at", table_name="news_pipeline_runs")
    op.drop_table("news_pipeline_runs")
    op.drop_index("idx_source_name", table_name="news_articles_raw")
    op.drop_index("idx_published_at", table_name="news_articles_raw")
    op.drop_index("idx_provider_article_id", table_name="news_articles_raw")
    op.drop_index("idx_ingest_hash", table_name="news_articles_raw")
    op.drop_table("news_articles_raw")
    op.drop_index("idx_top_level_category", table_name="news_articles_processed")
    op.drop_index("idx_signal_score", table_name="news_articles_processed")
    op.drop_index("idx_raw_article_id", table_name="news_articles_processed")
    op.drop_index("idx_processed_at", table_name="news_articles_processed")
    op.drop_table("news_articles_processed")
    op.drop_index("idx_user_article", table_name="news_article_matches")
    op.drop_index("idx_matched_supplier", table_name="news_article_matches")
    op.drop_table("news_article_matches")
    # ### end Alembic commands ###
