"""Category normalization helpers for personalization."""

from collections.abc import Iterable

CANONICAL_CATEGORIES = {
    "automotive",
    "electronics",
    "chemicals",
    "raw_materials",
    "metals_mining",
    "energy",
    "manufacturing",
    "logistics",
    "packaging",
    "construction",
    "food_agriculture",
    "pharma_healthcare",
    "aerospace_defense",
    "retail_consumer",
    "technology",
    "finance",
    "labor",
    "geopolitical",
    "sustainability",
    "regulatory",
    "general",
}

CATEGORY_ALIASES: dict[str, str] = {
    "auto": "automotive",
    "automobile": "automotive",
    "automobiles": "automotive",
    "car": "automotive",
    "cars": "automotive",
    "ev": "automotive",
    "evs": "automotive",
    "vehicle": "automotive",
    "vehicles": "automotive",
    "chip": "electronics",
    "chips": "electronics",
    "electronic": "electronics",
    "semiconductor": "electronics",
    "semiconductors": "electronics",
    "tech": "technology",
    "software": "technology",
    "saas": "technology",
    "cloud": "technology",
    "artificial intelligence": "technology",
    "ai": "technology",
    "chemical": "chemicals",
    "commodity": "raw_materials",
    "commodities": "raw_materials",
    "raw material": "raw_materials",
    "raw materials": "raw_materials",
    "critical material": "raw_materials",
    "critical materials": "raw_materials",
    "metal": "metals_mining",
    "metals": "metals_mining",
    "mining": "metals_mining",
    "critical mineral": "metals_mining",
    "critical minerals": "metals_mining",
    "lithium": "metals_mining",
    "copper": "metals_mining",
    "steel": "metals_mining",
    "freight": "logistics",
    "shipping": "logistics",
    "supply chain": "logistics",
    "supply_chain": "logistics",
    "transport": "logistics",
    "transportation": "logistics",
    "factory": "manufacturing",
    "factories": "manufacturing",
    "industrial": "manufacturing",
    "industry": "manufacturing",
    "pack": "packaging",
    "packaging": "packaging",
    "container": "packaging",
    "containers": "packaging",
    "building": "construction",
    "construction": "construction",
    "infrastructure": "construction",
    "agriculture": "food_agriculture",
    "agri": "food_agriculture",
    "food": "food_agriculture",
    "farming": "food_agriculture",
    "crop": "food_agriculture",
    "crops": "food_agriculture",
    "pharma": "pharma_healthcare",
    "pharmaceutical": "pharma_healthcare",
    "pharmaceuticals": "pharma_healthcare",
    "healthcare": "pharma_healthcare",
    "medical": "pharma_healthcare",
    "aerospace": "aerospace_defense",
    "defence": "aerospace_defense",
    "defense": "aerospace_defense",
    "consumer": "retail_consumer",
    "retail": "retail_consumer",
    "finance": "finance",
    "financial": "finance",
    "currency": "finance",
    "fx": "finance",
    "labor": "labor",
    "labour": "labor",
    "workforce": "labor",
    "geopolitical": "geopolitical",
    "geopolitics": "geopolitical",
    "war": "geopolitical",
    "conflict": "geopolitical",
    "sustainability": "sustainability",
    "climate": "sustainability",
    "emissions": "sustainability",
    "esg": "sustainability",
    "compliance": "regulatory",
    "legal": "regulatory",
    "regulation": "regulatory",
    "regulations": "regulatory",
    "oil": "energy",
    "gas": "energy",
    "power": "energy",
    "renewable": "energy",
    "renewables": "energy",
    "utility": "energy",
    "utilities": "energy",
}

CATEGORY_KEYWORDS: dict[str, set[str]] = {
    "automotive": {
        "automotive",
        "auto",
        "automobile",
        "car",
        "cars",
        "ev",
        "fleet",
        "mobility",
        "vehicle",
        "vehicles",
    },
    "electronics": {
        "chip",
        "chips",
        "electronics",
        "hardware",
        "memory",
        "semiconductor",
        "semiconductors",
    },
    "technology": {
        "ai",
        "artificial",
        "cloud",
        "cybersecurity",
        "data",
        "digital",
        "saas",
        "software",
        "tech",
        "technology",
    },
    "chemicals": {
        "chemical",
        "chemicals",
        "fertilizer",
        "plastics",
        "polymer",
        "resin",
    },
    "raw_materials": {
        "commodity",
        "commodities",
        "material",
        "materials",
        "raw",
        "shortage",
    },
    "metals_mining": {
        "aluminum",
        "copper",
        "critical",
        "lithium",
        "metal",
        "metals",
        "mineral",
        "minerals",
        "mining",
        "nickel",
        "rare",
        "steel",
    },
    "energy": {
        "battery",
        "electricity",
        "energy",
        "gas",
        "oil",
        "power",
        "renewable",
        "renewables",
        "solar",
        "utility",
        "wind",
    },
    "manufacturing": {
        "factory",
        "factories",
        "industrial",
        "industry",
        "manufacturing",
        "plant",
        "production",
    },
    "logistics": {
        "cargo",
        "freight",
        "logistics",
        "port",
        "shipping",
        "supply",
        "transport",
        "transportation",
        "warehouse",
    },
    "packaging": {
        "bottle",
        "box",
        "container",
        "containers",
        "pack",
        "packaging",
        "paper",
        "pallet",
    },
    "construction": {
        "building",
        "cement",
        "construction",
        "infrastructure",
        "lumber",
        "project",
    },
    "food_agriculture": {
        "agriculture",
        "crop",
        "crops",
        "farm",
        "farming",
        "food",
        "grain",
        "wheat",
    },
    "pharma_healthcare": {
        "drug",
        "healthcare",
        "medical",
        "medicine",
        "pharma",
        "pharmaceutical",
        "pharmaceuticals",
    },
    "aerospace_defense": {
        "aerospace",
        "aircraft",
        "aviation",
        "defence",
        "defense",
        "military",
    },
    "retail_consumer": {
        "consumer",
        "demand",
        "retail",
        "store",
        "stores",
    },
    "finance": {
        "currency",
        "finance",
        "financial",
        "fx",
        "inflation",
        "rate",
        "rates",
    },
    "labor": {
        "labor",
        "labour",
        "strike",
        "union",
        "wage",
        "workforce",
    },
    "geopolitical": {
        "conflict",
        "geopolitical",
        "geopolitics",
        "military",
        "sanctions",
        "war",
    },
    "sustainability": {
        "carbon",
        "climate",
        "emissions",
        "esg",
        "sustainability",
        "sustainable",
    },
    "regulatory": {
        "compliance",
        "law",
        "legal",
        "policy",
        "regulation",
        "regulations",
        "regulatory",
        "rules",
        "sanctions",
        "tariff",
        "trade",
    },
}


def normalize_category_key(value: object) -> str:
    """Return a stable lowercase key for category matching."""

    text = str(value).strip().lower().replace("-", " ").replace("_", " ")
    return " ".join(text.split())


def canonical_category(value: object) -> str:
    """Map common user-entered category names to the article taxonomy."""

    key = normalize_category_key(value)
    if key in CANONICAL_CATEGORIES:
        return key
    if key in CATEGORY_ALIASES:
        return CATEGORY_ALIASES[key]

    tokens = set(key.split())
    scores = {category: len(tokens & keywords) for category, keywords in CATEGORY_KEYWORDS.items()}
    best_category, score = max(scores.items(), key=lambda item: item[1])
    return best_category if score > 0 else key


def canonical_category_list(values: Iterable[object] | None) -> list[str]:
    """Canonicalize category values while preserving input order."""

    normalized: list[str] = []
    for value in values or []:
        category = canonical_category(value)
        if category and category not in normalized:
            normalized.append(category)
    return normalized


def canonical_category_set(values: Iterable[object] | None) -> set[str]:
    """Canonicalize category values for set operations."""

    return set(canonical_category_list(values))
